#!/bin/bash
rm -f /usr/share/texmf/tex/generic/0magyar
#(cd /usr/share/texmf && (for F in tex/generic/babel/{magyar.ldf,huhyph*.tex}; \
#  do test -f "$F.not" && test ! -f "$F" && mv -f "$F"{.not,}; done; true))
mktexlsr /usr/share/texmf
